import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Pages here are generated by scripts/sync_vault.py; the tree follows the folders.
const sidebars: SidebarsConfig = {
  guideSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
