import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated folders (scripts/sync_vault.py): guide/ and components/ become the two sections.
const sidebars: SidebarsConfig = {
  developmentSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
